// This file contains the sample responses and request data. c'mon i cannot scrape 100s of comments again and again. i'll evntually delete this
export const comData = [
  "Perfect late night vibes from Sneha 🖤",
  "Convinced this is written by a mother about her children. It always makes me think of my babies. ❤",
  "This sounds like what I think falling in love is like. Like not just any love. That one special fairytale romance love. The kind of love that you only find once. So this is Love.",
  "When I listen to this song…\n\nI picture myself waking up in white sheets, little rustic room in Paris. Sunlight beaming through open wooden shutters onto the tile paved balcony with a soft breeze caressing the curtains. Seeing the Eiffel Tower in the sunlight making friends with the fluffy white clouds painted on a soft baby blue sky and my lover next to me….. perfection ❤️",
  "Her voice is so youthful, sweet and feminine!  Amazing ear candy!  And the beautiful piano makes this one of the loveliest pieces of music I have ever heard.",
  "I loved this song from a Disney movie, but her voice showed me what true love REALLY is.",
  "Been crying all morning listening to this beautiful song thinking of my beloved son 💙 🙏🏽🕊",
  "So this is love, mmm\nSo this is love \n \nSo this is what makes life divine \nI'm all aglow, mmm\nAnd now i know\nThe key to all heaven is mine\n\nMy heart has wings, mmm\nAnd i can fly\nI'll touch every star in the skyl\n\n\nSo this is the miracle\nThat I've been dreaming of \nMmm, mmm\nSo this isss loveee\n\n(Instrumental)\n\nMmm, mmm\nI'll touch every star in the sky \nSo this is the miracle \nThat I've been dreaming of\nMmm, mmm\n\nSo this isss loveee",
  "Been singing this song lately to Jesus just randomly without hearing it since I was a little girl. What a crazy ride this has been ☺️💕✨",
  "The only problem I have with this song is that it’s so short! \nThis sounds like the purest form of love, a love that runs deep and lasts forever 🥰",
  "It’s giving real Christmas vibes. Sitting under the mistletoe drinking hot cocoa and marshmallows 🥹❤️ so divine✨",
  "A voice as divine as her’s….\n\n Truly there is a God",
  "My imagination in this song:\n\nMy husband and I came to house together, he takes off my coat, kiss my lips, than we hug each other, I go to the kitchen and prepare a pie, my husband comes and hugs me from back, kiss me and we prepare a pie together, listening our favorite music and dancing to it, then we go to balcony and eat together, drinking green tea and enjoying the view of Eiffel tower when there is a pink sunset 🌇. It's so romantic. And when we are at old age, we are doing the same thing and we are happy together. \n\nAlso, I imagine how we travel together in our own car around the world, there is a soft wind blowing to our face, we kiss, and be ourselves, dancing under the rain, laughing and making jokes with each other. We are under the moon in our car, lying by hugging each other. \n\n🥰\n\nP.S. sorry for some mistakes! I'm not a native user of English",
  "No cover of this song has pleased my heart and soul as much as this one has.\nThis one will be perfect for a first wedding dance accompanied with elegant choreography.",
  "I got chills with every note you hit",
  "2 things come to mind and touch my heart when I hear this song. The first one is the very moment I held each one of my babies right after giving birth… honestly the biggest love I have ever felt. Indescribable honestly!! And the Second one goes back to my childhood to my very first love, my grandma. It shifts me there to her living comforting arms. What a lovely song and what a lovely voice, lovely melody 😍😍😍",
  'My representation of this song is something like about God\'s Love to us. Unending, Unyielding.  When I hear this \n"So this is Love, this is what makes life Divine" Indeed it is love :)',
  "Beautiful 🤩 elegant, feminine, crispy, playful, gorgeous. What a beautiful tune, what a beautiful song, what beautiful fillings it evokes ❤️",
  "Oh, Gosh, this song is so nice. I can't stop listening to this song. ❤❤",
  "This sounds like Christmastime ahhhhhh. I imagine running though times square on a cozy winter day, snow falling everywhere with someone special by my side. Absolutely in love with this.",
  "I love it without any video clip and not too much musical instruments or effects , that I can feel the lyrics ..",
  "I can play this over, and over, and overrrrrrrrrr. Such a beautiful version!!!!!!!!!! I’m holding my 3 month old son now as he’s sleeping and this has been on repeat for like 30 mins now❤",
  "I love how she took the original and elevated it. It's very difficult to do but this is exactly what my heart is and why I often feel like I was born in the wrong era. Thank you for this.",
  "This is sung perfectly! I love it.",
  "Absolutely BEAUTIFUL! I have NEVER heard this song covered this way. You still made it your own without taking away from the original. I LOVE this cover!!!! 🥰",
  "loving this vintage vibe\n\n:virtualhug:",
  "Wowow one of the most  melodious voices I've ever heard🙌🎧❤",
  "Una voz angelical!!!",
  "Relaxing music and it makes me in love deeper to the person i love ❤️",
  "Beautiful rendition👌🖤",
  "This is the most beautiful thing I ever heard in my entire life 🥲 good God, I don't think any voice can be sweeter than this.",
  "I love the natural, non-synthetic quality to her voice. Pure bliss",
  "Daaam bro I've never been send to another world like this song Man we even have a piano a beautiful singing voice even have bird's chirping the sound of gentle wind awhile chilling outside in nature with your partner and have private picnic together and this song playing on the background awhile you chat and have fun with each other",
  "angelic voice, angelic song 💞",
  "this song hits different when your just experiencing your first TRUE love, not a stupid crush\nSo this is love! it feels soo good",
  "0:22 that riff tho 👌🤌✨",
  "Essa música é linda ❤",
  "Manifesting this year I meet someone that I will be able to listen to this song and relate to if because of them <3",
  "Wow 😍🥰 love this  version 🤩",
  "Love love love her voice! So perfect for this song!",
  "Love Is just something special. I can't but in words it's just beautiful",
  "This is the best song to listen in the Sunday morning❤️",
  "Perfect song to wake up to! Life is LOVE ❤️",
  "So so beautiful. The roll in your voice is so sweet.",
  "Perfect song ❤",
  "I can feel the music from their soul to my own. Perfection.",
  "BEAUTIFUL VOICE!!!!!! ❤❤",
  "Im falling deeper in love with them love feels like time has stopped whenever the two of you are together, when you look into their eyes you see you're future with them. I just wanna hold them in a enternal hug just for making me this happy",
  "Magnificent ❤️",
  "this is so beautiful 🖤",
  "The pianist is a jazz legend 🔥\nThe voice is angelic 😇",
  "Lovely song!💖",
  "My goodness...\nThis is beyond beautiful 🥺😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍",
  "Her voice is beautiful",
  "The most beautiful song I've heard😍",
  "This song is perfection.",
  "I breath deeper listening to this. Can this be our wedding song as I walk down the aisle 🤍🤍🤍\nLove so devine",
  '✨"When i hear this song"✨\n\n❤✨I always feel like im at a beach at night. star gazing,  the sea roaring,  the wind ceressing my face,  beneath the trees,  next to my "lover" passionate❤✨',
  "She sounds soo perfect 🥰",
  "calming song ️☺️👍🏻",
  "This song makes me want to tap more into my head tones.... I LOVE IT!!! Every BIT of it!!! Her approach to the melody, riff/run placement, head tones is EVERYTHING!!!",
  "I’m listening to this and singing along whilst holding my beautiful newborn and he is drifting asleep in my arms 💙\nSo this is love…",
  "When I listen to this song it makes me imagine I'm sitting by the beache's shore observing the sun being rose reminding me of cotton candy. Taking a deep breath and closing my eyes as I move my head to my lovers direction opening my eyes to see his caramel eyes looking at me with desire. He leans in to kiss me with his pink soft lips that taste like bubblegum peach. His lips met mine, kissing me with his desiring love for me. Him, His touch heals my anxiety, warming my heart. Waking up, I sighed as it was just another dream.\n\nGuys I'm bad at poetry but I tried hehe",
  "Can we pls all just take a moment to realize that there is no other song this beautiful, gently, heart aching. This song goes out to all of those hopeless romantics that finally found their happy ever after, after searching for it for years! And its a nice reminder to the other hopeless romantics that are still looking that there is hope for us. Never did I think a song like this would bring me tears every time! 💖💖💖💖",
  "When I was pregnant with my son, he love the Disney version. He always moved when I play that song. A view days ago I found this version, now he sleeps listening to this song.",
  "HER VOCALS ARE SO SMOOTH THAT THEY'RE VERY SOOTHING NOT ONLY TO YOUR EARS, BUT TO YOU SOUL!!!! NOW THAT'S SINGING TALENT!!!!#PRAISETheCREATORofALL",
  "I always loved this song on Cinderella but this is sooooooooo beautiful!",
  "This song is so peaceful and beautiful it puts my 4 week old baby right to sleep when nothing else can soothe her this song does it ! ❤",
  "I like it so calming",
  "This song reminds me my childhood love fairytale … Cinderella …. ❤",
  "I love it. She sounds like my perfect 40's oldies. I want more ❤️",
  "I like this music 🎶 🎵 😌 👌 😍",
  "This is me and my gfs song “our song” it’s just perfect she chose it she came across it on TikTok after I mentioned to her to pick a song for us that we dance to and cuddle to and relate to its srsly perfect",
  "her tone changes so beautifully it reminds me of those mellow pastel anime songs uhh vocaloid",
  "🙇🙇🙇🥲🙃🙃🙃 this is the perfect voice to fall in love with... The best i heard to date.",
  "This is so beautiful!",
  "This song takes me to the imagination where i meet my baby pet feels my heart so full, all i want is to see her again and make my heart complete... I live in LONDON so far away from her... I miss u baby girl...",
  "When i listen to this i remember holding my daughter & son as newborns",
  "Divine is this art, not that love she’s singing about 😂👏🏻🔥",
  "Que dulzura en esta voz y melodia",
  "A pure jewell...",
  "This song is sooo lovely ❤😅 it makes me think my baecation in Paris 😊",
  "So beautiful ❤❤❤ thank you 🙏",
  "I love this jazz version 🤌💋",
  "I end up crying out of nowhere,but its fine.im happy now i know somehow theres someone who loves me",
  "Soothing Lovely song, beautiful but sad at the same time, makes me think of live lost",
  "J'adore ❤️🌟",
  "Mm so peacefully sang I love it so much ❤❤❤❤❤❤❤❤",
  "so this is love ❤",
  "I feel like Id play this is what falling in love feels like and then straight to this🖤",
  "A true slow dance song at a prom",
  "I heard this soooooo long ago and it's the background sound everytime I see my girlfriend 🥺🔥",
  "Beautiful ❤",
  "The classics :)",
  "feeling like a princess..<3",
  "This is stunning ❤️❤️❤️❤️🥰🥰 *rewinds",
  "Her voice make me feels like im Flying, it makes me imaging myself with my crush",
  "love this",
  "A quand un album ❤❤❤",
  "It feels like im falling in love in paris how romantic",
  "When...this is so cute that you are in peace...this is so cute 💕",
  "짱좋아여 ㅠㅠㅠㅠ",
  "So good!!!!",
  "This song makes me feel like im dancing on a cloud living in my daydream about finding my price charming and dancing the night away \n\n\n\n\ncutely Twerks in royal",
  "Mmm, So this is love, mmm, so this is love~ SoOoOOoO This is what makes life diviNEEE. Im all aglow, mmm, And now I know~ The key to all heaven, is mine~ My heart has wings, mmm, and I can fly~ Ill touch, every star in the sky~ So this, is the miracle, That ive been dreaming of.. Mmm, MMMMMMMM, So this issss, looooove~",
  "Beautiful 😍",
  "I always adored this song from Cinderella and I sing it all the time, but this thissss though 🥺👉🏾👈🏾",
  "Perfect💓",
  "I melt down every time i listen to that song",
  "This Remake is absolute 🔥🔥 My Favorite Disney Song with FLAVA!! Who is this Vocal Creature!?!?!",
  "Omg I miss this song , haha what a  lovely little song",
  "Call me weird but I found this song in a roblox game and I was looking WILDLY for it. I loved the voice and I instantly fell in love. Now here I am listening to this on repeat 😭😭",
  "So this is more like relax drink some wine late night looking at the stars,  and this song yumeyyyy",
  "It's so beautiful",
  "I love it",
  "Could anyone recommend a few more songs of similar vibe?",
  "Zum Träumen schön❤️❤️❤️",
  "Oh God my heart ❤️",
  "I find it better than original actually~",
  "It’s almost criminal how little views this has.",
  "It's July 2022 ! let's see how many legend and fans are stills listening to this masterpiece...💜❤💫〽️",
  "It was December, went to a cafe. It was evening but her eyes were as bright as the sun. It was cold but her stares were warm.....\n\nPlease continue with your imagination 🙂.....",
  "Got damn...she made me melt",
  "Shit made me cry … and miss my granny",
  "Omg... perfect",
  "Somehow I came all the was from listening to this in roblox fantasia to searching it up and putting it on my playlists bcs how beautiful it is",
  "Beautiful",
  "Me when I finally get to cuddle with my cat after a long day:",
  "🔥🙌🏽🎯",
  "The best👌",
  "It's July 2022 💟 let's see how many legend and fans are still listening to this masterpiece...💚❣️💛🎊💖",
  "😍😍😍😍",
  "𝙥𝙧𝙤𝙢𝙤𝙨𝙢 💞",
  "My imagination of this song is that I can see Mickey and Minnie dancing in the living room while this song is playing on the radio and then they share a kiss at the end of the song",
  "Her voice….",
  "Why I can’t stop crying while listening this..",
  "I want whatever she was sipping and go there. Wow how beautiful 😍",
  "Fire song",
  "God is Love.\nPraise God, Praise Love.",
  "Wow so beautiful song",
  "With this song I just picture love itself",
  "This song sounds like when you fall for the wrong person and think they love you so you accept it because you think this is the meaning of love.",
  "Lovely...",
  "makes me wanna sleep now lol",
  "So Calming",
  "Perfect",
  "♥️♥️♥️♥️♥️",
  "❤️ Love ❤️",
  "An Angel",
  "💜💜💜",
  "❤",
  "😍",
  "Very slow but very calm.",
  "All babies wish their moms sound like this.",
  "Isn’t this song from Cinderella?",
  "Disney looking for sneha",
  "🤍",
  "I love this song. But I just don't like that effect or auto tune she has",
  "❤❤🥲🕊",
  "Thanks facebook music",
  "What's the point of steal a song, change the background and add lyrics? At least share the link to the original",
  "1:23 ~",
  "teh besst",
  "Me🤣",
  "0:56",
  "I heard this on a roblox game called Fantasia if anyone wants to go play it",
  "To many runs, childlike voice. I like the original better. She can sing, pretty voice.",
  "Horror",
  "Oooooo",
  "hey",
  "To \nMy favorite person.  \nSub-black magic level 10 used on you\n\nRespectfully, \nI used black magic on u with the help of cute doll n a needle to make you fall in love with me i.e from 5/2/23 to x/x/xx, as u can see the effect n also feel the effects 😋\n\nYour sincerely \nBomz+eliza(My Favorite person)\n5/2/23",
  "4th comment",
  "lpppppp",
  "no",
  "The piano is DISGUSTING",
];

const res = [
  {
    message: "total 171 comments analysed ",
    data: [
      {
        emotionName: "neutral",
        intensity: 0.35207356144849417,
        frequency: 0.3157894736842105,
        comments: [
          "This channel puts in the work!",
          "Wouldn’t it be much more effective to at least partly grow hemp instead of planting trees in temperate regions? Hemp can be used immediately as a source for paper, building materials (hempcrete), textile, etc. CO2 is sequestered from day 1, instead of after 8 years onwards. It also much more flexible. The amount of CO2 sequestration is the same, if not more, than that of the beeches and softwoods in the documentary.",
          "People who plant trees should be awarded and highly respected\nPlease let's take care of our planet, there're still a lot of people who lack enviromental consciousness, a lot!",
          "Feels like Captain Pollution has Captain Planet in a death grip.",
          "Its possible climat neutral is a cover from corporations and those controlling the systems. To stay in contol when the inevitable decline happens and a new system is in place by their choosing to remain in contol... in other words controlling the decline and the mess thats made in name of something ells.",
          "May the Anthroprocene epoch make the Permian-Triassic extinction event seem like a minor footnote in the pages of Earth's history. Here's to making scenario SSP5-8.5 of the IPCC assessment a reality.",
          "Humanity is a heat engine, no matter how you slice it.",
          "Nature💚",
          "Remove the print and paint colours on the labels, tons of harmful chemicals will be removed from the environment, less energy to process the labels and it makes it easy to recycle the plastics.",
          "It means poor people eat bugs and don’t have electricity. \nWhile rich people fly planes and eat meat.",
          "This should be applied to the context of higher education in emerging countries: Is program-accredited (by accreditation institutions) a lie?",
          "Data Science for exactly this.",
          "Per Capita Emissions are more important than total emission of a country.\nSimilarly Historical Emitters developed countries have Bigger responsibility. \nCommon but differentiated Responsibilities for developing countries.",
          "Trees take fresh water  , trees take rain to grow 🤔",
          "? I think the amount of co2 and the amount of biomass finally is in the very same scale.\nthe carbon binds in corbonhydrates. and finally is burned after being cut and used, e.g. as building material, its reduced to co2 of course.\nSo the woods stores the carbon for its nature span.\neach wood falling down will mainly be reclaimed by microorganisms creating co2. \nand very few will become earth too. for some time.",
          "in my years we lost 13 elm, trees\nsince then 30 year ago\nwe planted 42 ash trees and in a muddy hollow 15 willow\nthey are 30 years old i think iv done my bit\nin fact we cant plant any more no space",
          "Conclusion: carbon offsetting is a loophole actively acting against reducing carbon emissions",
          "The IPCC definition of neutral says emissions not just C02! A long way to go to stop the 2nd law of thermodynamics",
          "Until the airline industry shuts down or limits the numbers of flights around the globe nothing can save this planet.",
          "You need energy to plant so net positive energy use",
          "There was a climate crisis that destroyed civilisations, and that was about 3000 years ago. It is an irrefutable fact that as CO2 levels increase then plant growth does also. \r\nCO2 at 1000ppm [ three times present levels] is possibly optimum for forests, agriculture, and deserts.. If we could increase levels of CO2 to optimum levels of about 1000ppm \r\n the forests would flourish; the deserts would become productive; and the imminent destruc-tion of agriculture now sought would make many countries even a greater exporters of food ; plentiful for the world,   Commercial green houses use these facts for high yield and profitability.\n And of course human societies go well during the warm periods. \r\nOlder people flock to warmer areas at retirement. The climate threat is a globalist scam to redistribute wealth upwards yet again.\r\n\r\nWith the knowledge that  Co2 rises after warm earth periods not before as  we are conditioned to think by the fraudulent climate control  freaks. \r\n In any event human civilizations have always  been more successful in warmer periods.\r\n Commercial green houses use these facts for high yield and profitability .\nConversing with a luddite climate activist is as useful as discussing physics with a frog.",
          "My home is truly net zero",
          "Industrial society can, and never will be sustainable.",
          "The used EV I'm driving \"....",
          "CO2 is not a driver of warming. Historically, CO2 levels has risen AFTER warming, so it can be a result, but not the cause.",
          "Humans are very good at deluding themselves. Which do you think is the correct answer:\na) plant more trees\nb) cut down on carbon emissions\nc) decrease population",
          "Marine life is the reason for the oxygen you breathe today",
          '"How much CO2 can a tree absorve?" not more CO2 then you issue traveling by car to plan the tree',
          "As,attainable as a perpetual motion machine.",
          "The responsibility lies in us, not these bs companies that deceive us. Cut down on meat & seafood consumption. Cut out fast fashion & fast furniture.",
          'It is not "offsetting" but hiding co2. co2 will be released when tree is burnt. problem is wasteful economy model not  co2 emissions.',
          "Cholesterol free, Organic and now Climate Neutral. All marketing gimmicks. It's all big business.",
          "It’s all marketing hype…  while others get rich. For example planting trees is only a work around, not a solution.",
          "If you think you can't affect the climate you don't understand physics.",
          "Do not cut those trees..",
          "8 billion x 800 = 6.4 trillion trees 😅",
          "They plant here and for their consumer needs they use trees from third countries. Another in a series of  Western hypocrisies.",
          "Lead, Snake oil, fat free, sugar free, Akin, Kale, Gluten free…",
          "Drill baby, drill.",
          '...                                                                                   BY   "COMPANIES"  YOU MEAN   "OIL  COMPANIES"\n...                                      NO ?\n...                                                                           "CHEMICAL COMPANIES"  AND/OR  "PLASTIC COMPANIES"',
          "They were planting dead trees",
          "you may restore forests by planting trees but not biod versity",
          "CCPI (Climate Change Performance Index) rankings are published recently. \nLook at some pathetic countries that claims they are proactive against Climate Change, making others to pledge Carbon neutrality,\n but themselves ranks very low.\n\nPer Capita Emissions are more important than total emission of a country.\n\nSimilarly Historical Emitters developed countries have Bigger responsibility.\n\nCommon but differentiated Responsibilities.",
          "O! And Nitrogen, hydrogen,  helium and all the other gases that keep this earth going.",
          "Humans live On and Of Nature, Animals live In and With Nature, whom of these two will Always destroy Nature.",
          "Yes\nNext question",
          "HBO John Oliver tackled this farce.",
          "Global 2 kids policy.",
          "And its 4 mins ago !!",
          "We can create negotiated borders of trees, and alternative energy production and sharing only  in a peace economy...perhaps that's why the USA is so keen to  proliferate . In its attempt to cause wars In Korea, with the Chinese, Israel  and it's oppression of Palistine and just about ever corner of the world including   Ukraine ...Along with  the manipulation of NATO  and UN ECT ,..is to keep the fossil fuel industry grinding along at any cost, whilst selling arms.. It's apparant the USA will go to any lengths to creat WAR culture and desperate economy💟❣️💌🍄🥀🌹💐🌈⭐🌏🌎🌍🍐🍏🥝🦋🐞🐃🐂🐄🦕🦖🐉🐽🌿🌱🍃☘️🌲🌳🌴",
          "Main reason no plantation by humanity",
          "It's a bit like carbon offset... a load of BS.",
          "To these worshippers of Gaia - repent for the Kingdom of God is at hand!",
          ":yougotthis::elbowcough:🌱🪴🌲🌳:washhands::washhands::washhands::socialdist:",
        ],
      },
      {
        emotionName: "approval",
        intensity: 0.12273837611530311,
        frequency: 0.11695906432748537,
        comments: [
          "using petrol to plant a tree, now that's what I call efficiency",
          "Another great documentary by DW regarding climate change.Keep it up 👍.",
          "Whilst there are questionable practices and a lack of standards, it's better to do some positive than none.",
          "Corporations are all about carbon offsetting because it sounds good, just like the video says. But more important is finding ways to outfight reduce carbon emissions outright.",
          'Yes "Greenwashing" is a sleazy tactic used more and more by these sleazy, tax-deferring, corporations. Thx DW!!! We all need to understand that not everything is as it appears. 👍',
          "True 💯💖",
          "Plant my tree in this recently clear cut area, looks nice on the balance sheet.",
          "I very much agree that ' economic activity results in increase of carbon emissions \".  The man planting the trees will be able to produce more emissions himself because of his income from this tree planting scheme.",
          "Unconditional right to stop our own life whenever we want for all adults, my body my choice.",
          "This broadcast is 'Safe and Effective'. Sunny ways people!",
          "3:34 A good hold 2 time engines, that thing pollute probably more than the tree they plant will absorb in CO2 over is life. Let's not talk about the big truck they use to move around. All that for a few dozen trees of a few species. The better way would be to put a light fence around the area and let nature do it's things ... +",
          "Humanity has been clearing forests for thousands of years, to provide grazing, grain farming, building, burning from Malta through Europe, the America's, New Zealand, Australia even Easter Island and mother earth has accommodated it all, population collapse will do greater good than all the postering, imaginative marketing, rebranding etc.",
          "Enabling private individuals to offset their carbon print reduction by compensating them for cash is a move in the right direction. \r\nUnless all fellow humans subscribe unitedly to the personal, financially rewarding Carbon-reduction Scheme, we will not be able to stop the climate digression.",
          "How about Nuclear power, it would be a great energy source to use to produce everything for the renewable sources :D",
          "2022 2 species losing for climate change last year 2 species is okay. People must buy local products",
          "All Europe allow FREE catch of Green Energy at Home without taxes or fines. ⭐Green tránsition in 24h⭐",
          "sure plant 12 trees and keep driving a 4.8L, that will solve everything",
          "YES. NEXT",
          "Start with stop using plastics. That would go a long way. This should be the bare minimum and a starting point. We can use alternatives now. Promote the idea.",
          "tittle? yes...",
        ],
      },
      {
        emotionName: "curiosity",
        intensity: 0.11029467274298553,
        frequency: 0.0935672514619883,
        comments: [
          "“Reduced Climate Impact” would be a more appropriate product label.   Still how it’s defined matters.\n\nAlso, how about the distance it traveled and the refrigeration costs?",
          "Climate neutrality is now an impossible dream, after the Ukraine war. Germany is refiring coal power plants. New Zealand pushed its climate neutrality target from 2025 to 2050. If rich developed countries with resources can't do it, why expect developing countries with much greater basic needs to comply?",
          "Why are there no legal requirements for companies to offset their emissions?I would have thought that is it vital for governments to make this sort of thing compulsory.Anyway,I'll be taking a much closer look at the viability of carbon offsetting and trying to  hold companies accountable thanks to this informative documentary.Claims of climate neutrality need to be scrutinized very closely!! Maximum transparency is essential.Companies need to make the information public and easily accessible.",
          "What’s the background music with the pan drums that starts at 0:39?",
          "Can we evn mine enough minerals to create the EV's/batteries and solar/wind we will need?",
          "How many trees are they currently being cutting down for firewood in Europe this winter? As soon as it's a real inconvenience environmentalism is well forgotten.",
          "The more I see it the more it seems like the industrial revolution. That basically made a lot of rich people richer. Just like this.\nWhat good is it to offset your pollution if you just keep pumping it into the air? \nAny polluter mush be forced to capture carbon from it's manufacturing plant. \nElectric vehicles should not be allowed. They are very anti climate neutral.",
          'How about a documentary on the "Climate Death Cult" ?',
          "My gloves are so old they're sequestering carbon. They weren't black when I bought them. Can I get a Grant for that ?",
          "In my opinion, it would be much better to have a plan to plant more trees rather than try to switch to so called green energy and electric cars that will turn out to be much more toxic than we are being told. There are over 1 billion cars in the world. Assume they last 15 years on average. That means that 70 million need to be scrapped and recycled annually. What is going to happen to those 70 million highly toxic EV batteries annually? We are warned not to throw away AA batteries because they are toxic. EV batteries are enormous. This is going to be the next pollution crisis and I predict will be a bigger problem than a gas powered world auto fleet.",
          "What about the co2 footprint of the 80 million new souls we get each year,\nSo we should go vegan and drive a crappy ev so the population can keep growing?",
          "Climate propaganda.. 😂 how many threes has to be planted  for one volcano explosion?  Helloooooo",
          "Can the poor afford climate neutral?",
          "If there is no CO2 in the future, what are the trees going to breathe in?",
          "How long do climate change typical day our lives 😕",
          "Does a beech tree store carbon dioxide???  Doesn't a tree use carbon dioxide as part of its photosynthesis process?  Why the misinformation???\n\nIs zero emissions really feasible and practical?",
        ],
      },
      {
        emotionName: "admiration",
        intensity: 0.07817413883980796,
        frequency: 0.07017543859649122,
        comments: [
          "I'm glad that such big media platform is not afraid to speak about it. Make all the effort to research such issues!\nWell done DW!!",
          "Fantastic journal coverage 👌 about  climate Neutralized by increasing green areas- replanting  forests& reusing trash ...it's encouraging populations like Germany 🇩🇪 to mobilizes for a good, useful acting for climate neutrality in additionally of increasing ecosystem enlightening..my love and respect for  DW documentary channel 👏🏻 👍🏻",
          "Good documentary!",
          "Great channel",
          "Excellent report. Thank you.",
          "Big businesses see the label climate neutral as a great sales speech just like bio has been for years.",
          "Good documentary, definitely interesting, but it would be better to have more than only climate neutrality.  It is essential to also work against other forms of environmental pollution, destruction.",
          "It is possible and being done right now to reach climate goals with negative carbon footprint however the right boundaries have to be established and auditable and understandable accounting has to be done. \nSome of the true carbon removal technologies are pyrolysis to biochar, enhanced rock weathering, DACs etc. \nActual treeplanting as described in this program is a great idea however it does not have the longevity of the above mentioned to carbon removal methodologies. \nThe challenges that these other methodologies and at the very beginning of their lifecycle and literally $10-$15 trillion need to be spent over the next 5 to 10 years in order to not only stop CO2 emission increases but actually start reversing that trend and eventually reach an equilibrium point when we going to go after the existing CO2 imbalance in the atmosphere. In order to do correct carbon accounting scope one, two, three and four need to be accounted for.",
          "The climate tipping point got blown past decades ago. This is all smoke and mirrors to tamp down hysteria about the end is pretty much here. I applaud the efforts but realistically its one step forward, two steps back unfortunately.",
          "Good...",
          "How pathetic you clear-cut a forest to plant trees what a brilliant idea doesn't Mother Nature do that naturally duh",
          'We can\'t "make it", if you will. Good initiative and all that. But The mathematics will never add up. Resources taken from Earth over time. Millions up on millions of years. For god sake. We managed to screw it up in a hundred year span.',
        ],
      },
      {
        emotionName: "realization",
        intensity: 0.06805847608949392,
        frequency: 0.06432748538011696,
        comments: [
          "I used to believe in all these... Climate neutral , Fair Trade and everything organic marked..\nUntil I found out that, Big businesses come up with the clever ideas and created NGOs 🤣",
          "We have the climate of our consumption, we have the job of our consumption.\nThe only thing we have to change is our consumption behaviour that is it.\nAnd of course we have to educate young people in order to not letting them making the same mistakes of older generations.",
          "A few days ago where I live we broke the record for highest temperature for the\narea set back in the 1930's by 1 degree. It took all this time and after all the effort\nat environmental destruction the best we could do is 1 degree more.\nSomedays enduring all the doom and gloom just isn't worth the trouble.",
          "It's time to stop ignoring what's right in front of us. \nOver a decade ago the United Nations stated that a global shift towards a plant based diet is vital to save the world from the worst impacts of climate change. lts now 2022. The planet we call home simply cannot take the decimating impact of animal  agriculture any longer. \nEvery time we purchase animal products, we're supporting an industry that is either the main contributor, or a leading contributor to every major form of environmental devastation. \nDeforestation, water pollution, eutrophication, soil erosion, habitat loss, species extinction, ocean dead zones, plastic \npollution, greenhouse gas emissions, water use, land use, and the list goes on. There is no way to get around the fact that animal agriculture is destroying the Earth. It's time to change.",
          "Didn't know the Ukrainian president has a glove-making business on the side.",
          "Planting trees isn't just natural the version of BECCS. They also provide habitat and interact with fungi. The biodiversity is far more impactful to long-term climate change policy than specifically using trees as if they only have one function. That sense of scale and efficiency is what got us in this mess. We need elegant and robust systems that may not be profitable. It's not about apologizing for the excess carbon and then we get to go back to driving extinction in other ways. Stop compartmentalizing the problem and see what is revealed: the problem is capitalism.",
          "I believe that there is a natural climate cycle on Earth for millions of years BUT the our way of living since the Age of Industrialization just speeds it up ans makes it worse!",
          "This economical model we created by producing cheaply abroad and selling high back home is flawed in many aspects.\nTo hunt down methods to reduce CO2 emissions back home is ridiculous compared to the ecological destruction taking place in the nations of production.\nCountries like Bangladesh, or Vietnam, China are being slowly poisoned by our ways of making a buck.\nNot to mention the human costs of low wages and poor regulations.\n Forget about CO2.\nWe need to learn a brand new way of conduct to save ourself and the planet.\nIt becomes obvious though that we clearly will not be capable to move into a positive trend  for the future.\nSurvival of the fittest, maybe not!?",
          "'Climate' has been made a trademark, a currency - only to earn cash on it.",
          "Leftist and the Greens have used and misused semantics so much, that they have become almost unintelligible.  They have descended into a babbling that only they understand.",
          "And then the penny drops overpopulation overpopulation overpopulation....All efforts unless addressed are futile.....We know the regions to start......",
        ],
      },
    ],
    status: 200,
  },
];

/*

{
  "message": "total 27 comments analysed ",
  "data": [
    {
      "emotionName": "neutral",
      "intensity": 0.4526376737506576,
      "frequency": 0.37037037037037035,
      "comments": [
        "This is a problem all over the planet not just in France.",
        "The mad French chef archetype has a basis in reality",
        "Compared to the dolphins killed by the Japanese every year, it's a drop in the bucket",
        "Money said \"it could have been anything that caused this\".\nMoney said \"it wasnt my problem\"\nBut money was made and creatures have died.",
        "The frogs are apex predators in their own sere",
        "❤❤❤",
        "We humans rather trow a few billion into research for a bunch of stars billions of lightyears away (unreachable) then spending money on research to protect Earth species... \nThat's a Space Oddity...\n🐬🚀",
        "🫶🫶🫶🫶",
        "It is a pity more and more illegal immigrants get through, instead of being caught the same way",
        "Joe and Hunter Biden need saving as well.."
      ]
    },
    {
      "emotionName": "curiosity",
      "intensity": 0.17152145800747728,
      "frequency": 0.14814814814814814,
      "comments": [
        "How can public help? Please be specific.",
        "If noble dolphins can't avoid nets how can lowly hominids avoid nuclear Armageddon",
        "Why waste time discussing which coins to keep for the long term? Have you even heard of Papayahub?",
        "Who cares?\nWaging war and making profit is more important."
      ]
    },
    {
      "emotionName": "optimism",
      "intensity": 0.09585303956279366,
      "frequency": 0.07407407407407407,
      "comments": [
        "💔😥  Maybe some dolphins are drawn to the distress sounds and vibrations from fish that are caught & thrashing about in the nets? Hope they find a compromise design for nets, that won't trap dolphins.",
        "Yes save the Dolphins; we here in New Zealand have done well. But we have to do better!"
      ]
    },
    {
      "emotionName": "caring",
      "intensity": 0.05740078349093432,
      "frequency": 0.037037037037037035,
      "comments": [
        "We need to protect them for the existence and progression of humanity"
      ]
    },
    {
      "emotionName": "joy",
      "intensity": 0.056876985143836205,
      "frequency": 0.037037037037037035,
      "comments": [
        "Main reason why I stopped eating tuna decades ago. Nowadays I m  happy to be vegan"
      ]
    }
  ],
  "status": 200
}
*/